### ISSUE TITLE
(feature suggestion) Line-based binary reduction

### ISSUE THREAD

**Issue by rainoftime** [nafur/pydelta#1]
Hi,
I found the following tool quite useful for reducing the size of some formulas.
https://github.com/sambayless/linedd

It uses a simple, line-based mutation (just deleting some lines one time).
Perhaps pydelta can consider integrating similar strategies?

**Comment by nafur** [comment]
Thanks for the input.
Pydelta already has a mutator that erases children (https://github.com/nafur/pydelta/blob/master/pydelta/mutators_core.py#L21) which also applies to the top level node. This corresponds pretty much to "removing a line" (if you have one command per line).
What pydelta does not have is a mutator to erase multiple children at once. I'm hesitant to implement this, as it seems like a can of worms to me:
- while "remove one child" yields a linear number of candidates, "remove multiple child" yields exponentially many.
- as we can't just try all possibilities: which ones should we try?
- is it worth the hassle, given that we already have "remove one child"?

Have you had practical experience where this would have helped (a lot)?

**Comment by rainoftime** [comment]
Yes. I have some experience that the line-based binary reduction in linedd could help a lot. 
- try removing multiple lines at once, similar to binary search (since the lines have an order)
- the user can specify the fist and last line in the file for reduction

I had a case which has about 260 lines but contains more than 100,000 nodes. Removing one node at once could be slow in reducing the formula (even I used many threads)

**Comment by nafur** [comment]
In case you can reproduce this case: could you try with `--mode-aggressive`?
It guess this could be implemented (add a mutator that generates all the binary reductions and have a new mode that disables all but this one mutator).

**Comment by rainoftime** [comment]
The following instance might be useful for testing (for which z3 is much faster than CVC4)
[timeout.txt](https://github.com/nafur/pydelta/files/5588599/timeout.txt)

**Comment by nafur** [comment]
Ah, I see. I've used this example to do two important changes to pydelta:
- skipping (i.e. continuing from where it were after a successful mutation) is now done based on node counting instead of mutation counting. This avoids "over skipping" (where we would recurse into the node tree too soon).
- top-level binary reduction (as you suggested).

You can now do this "line-based" like reduction with `--mode-top-level-only`.
