### ISSUE TITLE
(feature) Diff mode

### ISSUE THREAD

**Issue by rainoftime** [nafur/pydelta#3]
Hi, to support differential testing, 
it would be useful to enable the comparison of two solvers.
In ddSMT, the command is as follows
~~~~
python ddsmt.py -c solver1 input.smt2 output.smt2 solver2
~~~~
Some notices:
- For incremental queries, the output of per query can contain many `sat/unsat`
- `solver` could be a solver combined with one or more options.
   A possible way is supporting commands like
    ~~~~
    pydelta -c "solver1 optA optB" input.smt2 output.smt2 "solver2 optC opt D"
   ~~~~

However, it seems that by default, pydelta does not support options for differential testing.

**Comment by nafur** [comment]
pyDelta does not support this itself on purpose: I found that there are way too many ways how exactly one would like to do differential testing to include this in the core tool. Instead, pyDelta ships with a script for this purpose (https://github.com/nafur/pydelta/blob/master/scripts/result_differs.py). Admittedly, I don't really know where this script ends up if you install it via pip, so you may just want to download it from github.
I found this solution way way more flexible (solver options, combined with timeout, more complex output matching, etc) and not polluting pyDelta itself.

**Comment by rainoftime** [comment]
Thanks!
May I ask how to use that script https://github.com/nafur/pydelta/blob/master/scripts/result_differs.py together with pyelta?
E.g., `pydelta script.py file.smt2`?
